#
# Database configuarion file
#

[development]
adapter = "postgresql"
encoding = "unicode"
database = "doboom_development"
username = "clu"
password = "password123"
host = "localhost"
port = 5432
pool = 5

[test]
adapter = "postgresql"
encoding = "unicode"
database = "doboom_test"
username = "clu"
password = "password123"
host = "localhost"
port = 5432
pool = 5

[production]
adapter = "postgresql"
encoding = "unicode"
database = "doboom_production"
username = "clu"
password = "password123"
host = "localhost"
port = 5432
pool = 5